name: Get GeoLite Database

on:
  workflow_dispatch:
  schedule:
    - cron: 0 13 */7 * *

jobs:
  clean:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  download_release:
    runs-on: ubuntu-latest
    needs: clean
    timeout-minutes: 5

    steps:
      - name: Download GeoLite Database
        run: |
          # 文件存放位置
          mkdir -p database
          
          # 下载IP数据库(mmdb)
          curl -LOJ "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${{ secrets.LICENSE_KEY }}&suffix=tar.gz"
          curl -LOJ "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${{ secrets.LICENSE_KEY }}&suffix=tar.gz"
          curl -LOJ "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${{ secrets.LICENSE_KEY }}&suffix=tar.gz"
          # 解压数据库
          for i in *.tar.gz; do
            tar -xvf "$i"
          done
          # 移动数据库文件到指定文件夹
          mv *.tar.gz GeoLite*/*.mmdb database
          
          # 下载IP数据库(csv)
          curl -LOJ "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN-CSV&license_key=${{ secrets.LICENSE_KEY }}&suffix=zip"
          curl -LOJ "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City-CSV&license_key=${{ secrets.LICENSE_KEY }}&suffix=zip"
          curl -LOJ "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=${{ secrets.LICENSE_KEY }}&suffix=zip"
          # 移动数据库文件到指定文件夹
          mv *.zip database
          
          # 时间戳
          echo "VERSION=$(echo GeoLite2-City_*.tar.gz | grep -Eo "[+-]?[0-9]+[0-9]+")" >> $GITHUB_ENV

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "database/*"
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
