name: Get GeoLite Database

on:
  workflow_dispatch:
  schedule:
    - cron: 0 13 */7 * *

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Download GeoLite Database
      run: |
        curl -LOJ "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${{ secrets.LICENSE_KEY }}&suffix=tar.gz"
        curl -LOJ "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${{ secrets.LICENSE_KEY }}&suffix=tar.gz"
        curl -LOJ "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${{ secrets.LICENSE_KEY }}&suffix=tar.gz"

        tar zxv *.tar.gz

        mkdir -p database
        mv GeoLite*/*.mmdb database

        echo "Time=$(date +"%Y.%m.%d")" >> $GITHUB_ENV

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 0
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "database/*"
        tag: ${{ env.Time }}
        token: ${{ secrets.GITHUB_TOKEN }}
